### ISSUE TITLE
[Solved] npm install error

### ISSUE THREAD

**Issue by tehseensagar** [EmpireProject/Empire-GUI#7]
running nmp install getting following error

29563 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
29564 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
29565 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
29565 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
29565 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
29565 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
29566 verbose stack Error: electron-chromedriver@1.8.0 install: `node ./download-chromedriver.js`
29566 verbose stack Exit status 1
29566 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
29566 verbose stack     at emitTwo (events.js:126:13)
29566 verbose stack     at EventEmitter.emit (events.js:214:7)
29566 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
29566 verbose stack     at emitTwo (events.js:126:13)
29566 verbose stack     at ChildProcess.emit (events.js:214:7)
29566 verbose stack     at maybeClose (internal/child_process.js:925:16)
29566 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
29567 verbose pkgid electron-chromedriver@1.8.0
29568 verbose cwd /opt/empire-gui
29569 verbose Linux 4.18.0-parrot8-amd64
29570 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
29571 verbose node v8.11.2
29572 verbose npm  v5.8.0
29573 error code ELIFECYCLE
29574 error errno 1
29575 error electron-chromedriver@1.8.0 install: `node ./download-chromedriver.js`
29575 error Exit status 1
29576 error Failed at the electron-chromedriver@1.8.0 install script.
29576 error This is probably not a problem with npm. There is likely additional logging output above.
29577 verbose exit [ 1, true ]

Regards

**Comment by tehseensagar** [comment]
If you getting any diffculty or issues like permission even running with sudo command , then you better run the following command 

download the latest package of empire from github in zip. 

Extract master.zip file  by unzip master.zip
change the directory to extracted  cd Empire-GUI-master

Now run the following command

`sudo npm install  --unsafe-perm=true --allow-root`

OR with Root login

`npm install --unsafe-perm=true --allow-root`

After sucessfull Installation of packges and modules 

`sudo npm start --unsafe-perm=true --allow-root`

OR

`npm start --unsafe-perm=true --allow-root`


OR

`sudo npm start`

OR

`npm start`

if you still have any issue you may contact me. I've tested this fix with my parrot OS 4.x

Regards
